- name: "iOS App Build and Deploy to iTunesConnect"
  language: objective-c
  os: osx
  osx_image: xcode10.2
  node_js:
    - "8"
  before_install:
    - brew update
    - brew install watchman
    - travis_retry npm install -g yarn
    - travis_retry npm install -g react-native-cli
    - gem install fastlane --version 2.112.0 --no-document --quiet
